after_success: |
  if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
    echo "$PGP_SECRET" | base64 --decode | gpg --import
    if [ -z "$TRAVIS_TAG" ]; then
        sbt publishSigned
    else
        sbt "sonatypeOpen \"opentracing-playframework $TRAVIS_TAG\"" publishSigned sonatypeRelease
    fi
  fi
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
deploy:
  api_key:
    secure: ABzKTyjMWd4PeU+GPz92WslRUhJOfEmfUDu9ws1Q4Ucl2/O11QI7fP8rREHo2DZYC3lOAToc7YfmnsavS8eRjKG+oM4hYxcjcaE82bhtzs4rCE6xffKqgACmty5c+UqKVdhjs1vCemYrE0WgbKWA8lfd30G5sp5lLiGfb8yzjx5oYPzQWqlzwZGqn8LVmyQi9SZLP+wgDmv06yoL8t4auSPE6Tn0tX470k7tpfBdWDA8Cm9/khrX3fCFmiHR3CJj7AWMwPyIfd8hZR3y5TB7M7PVBspLV/UXo2NIjubijkIQj1MisoxxeTzp/NMsA+87t2A2raTlhvt5xoUWd1j2SBFb+vbAsgZAPJEuiXTzWDrSZ1nSjrBeCWJbDXs2EnE5T0rox9IX7quMVTEG3H+c1KqDK/q1qScnkc186HzTctkdib8qjYGRwVsgG48IReKxT2p8/MDDO1SW03iECxXP4OSwd3A+Qqk0kYHUaJGLnlc4aWCk0c7Vm/WxCd/keY2cDq4N+Wf6Ial1mjwF2KMj4zzo4Cm8jrdTV4BNM2n+9UTI57ysebcNThpVXLIhT2ycKUoLVCXBOogjZM05k16UNyy9DlNTRPyRbQ3XCDCKcMqoG3APUv3bHzo9rSpwDT5zu1ZGmiHZoGGOhwGWuz7yuNoEqfhNG17JV4epS9XDFg0=
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk8
language: scala
script:
- '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
- sbt package
